# Generated by Django 6.0.6 on 2026-07-07 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="user",
        ),
        migrations.AddField(
            model_name="workspace",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
