# Generated by Django 6.0.6 on 2026-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_remove_workspace_user_workspace_collaborators_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifact",
            name="data_json",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="type",
        ),
        migrations.AddField(
            model_name="artifact",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artifact",
            name="title",
            field=models.CharField(default="exit", max_length=255),
            preserve_default=False,
        ),
    ]
