# Generated by Django 6.0.6 on 2026-07-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_remove_artifact_data_json_remove_artifact_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="artifact_type",
            field=models.CharField(default="markdown", max_length=50),
        ),
    ]
