# Generated by Django 6.0.6 on 2026-07-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_artifact_artifact_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="progress_state",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
